name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: |
        pip install --user platformio
        pio --version

    - name: Install dependencies
      run: pio pkg install

    - name: Build firmware
      run: pio run -e esp32c3_supermini

    - name: Verify firmware size
      run: |
        FIRMWARE_SIZE=$(stat -c%s .pio/build/esp32c3_supermini/firmware.bin)
        if [ $FIRMWARE_SIZE -gt 1048576 ]; then
          echo "Firmware size exceeds 1MB"
          exit 1
        fi

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: .pio/build/esp32c3_supermini/firmware.bin
        retention-days: 5

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: .pio/build/esp32c3_supermini/firmware.bin
        name: Release ${{ github.ref_name }}
        body: |
          Automated firmware release
          - Version: ${{ github.ref_name }}
          - Build date: ${{ github.event.head_commit.timestamp }}
          - Commit: ${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}