name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        pip install --user platformio
        pio --version

    - name: Build firmware
      run: pio run -e nodemcuv2

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: .pio/build/nodemcuv2/firmware.bin

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: .pio/build/nodemcuv2/firmware.bin
        name: Release ${{ github.ref_name }}
        body: Automated release with firmware
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}